/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as KnowledgeBasesImport } from './routes/knowledge-bases'
import { Route as IndexImport } from './routes/index'
import { Route as KnowledgeBasesCreateImport } from './routes/knowledge-bases.create'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeBasesRoute = KnowledgeBasesImport.update({
  id: '/knowledge-bases',
  path: '/knowledge-bases',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeBasesCreateRoute = KnowledgeBasesCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => KnowledgeBasesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge-bases': {
      id: '/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof KnowledgeBasesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/knowledge-bases/create': {
      id: '/knowledge-bases/create'
      path: '/create'
      fullPath: '/knowledge-bases/create'
      preLoaderRoute: typeof KnowledgeBasesCreateImport
      parentRoute: typeof KnowledgeBasesImport
    }
  }
}

// Create and export the route tree

interface KnowledgeBasesRouteChildren {
  KnowledgeBasesCreateRoute: typeof KnowledgeBasesCreateRoute
}

const KnowledgeBasesRouteChildren: KnowledgeBasesRouteChildren = {
  KnowledgeBasesCreateRoute: KnowledgeBasesCreateRoute,
}

const KnowledgeBasesRouteWithChildren = KnowledgeBasesRoute._addFileChildren(
  KnowledgeBasesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/knowledge-bases/create': typeof KnowledgeBasesCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/knowledge-bases/create': typeof KnowledgeBasesCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/knowledge-bases': typeof KnowledgeBasesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/knowledge-bases/create': typeof KnowledgeBasesCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge-bases'
    | '/login'
    | '/signup'
    | '/knowledge-bases/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/knowledge-bases'
    | '/login'
    | '/signup'
    | '/knowledge-bases/create'
  id:
    | '__root__'
    | '/'
    | '/knowledge-bases'
    | '/login'
    | '/signup'
    | '/knowledge-bases/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeBasesRoute: typeof KnowledgeBasesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeBasesRoute: KnowledgeBasesRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/knowledge-bases",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/knowledge-bases": {
      "filePath": "knowledge-bases.tsx",
      "children": [
        "/knowledge-bases/create"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/knowledge-bases/create": {
      "filePath": "knowledge-bases.create.tsx",
      "parent": "/knowledge-bases"
    }
  }
}
ROUTE_MANIFEST_END */
